name: Run Full Frontend E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies (if any)
        run: npm install

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Start backend server
        working-directory: backend
        run: |
          nohup npm run dev &

      - name: Start frontend server
        working-directory: frontend
        run: |
          nohup npm run dev &

      - name: Wait for servers to be ready
        run: |
          sleep 10
          curl --retry 10 --retry-delay 2 --retry-connrefused http://localhost:5173
          curl --retry 10 --retry-delay 2 --retry-connrefused http://localhost:3001

      - name: Run frontend E2E tests
        run: npx cucumber-js
